WebApplication1/Models/Admin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Admin
    {
        [Key]
        //ilk değeri key yapar
        public int AdminID { get; set; }
        [Column(TypeName ="Varchar(20)") ]
        //max giriş karakter syaısı
        public string Kullanici { get; set; }

        [Column(TypeName = "Varchar(20)")]
        //max giriş karakter sayısı
        public string Sifre { get; set; }

    }
}

WebApplication1/Models/Birim.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Birim
    {
        [Key]
        public int BirimID { get; set; }
        public string BirimAd { get; set; }
        public IList<Personel> Personels { get; set; }
    }
}

WebApplication1/Models/Context.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Context:DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("server= DESKTOP-O8UQ1L7\\SıLA; database=BirimDB; integrated security=true;");
        }
        public DbSet<Birim>Birims { get; set; }
        public DbSet<Personel>Personels { get; set; }
        public DbSet<Admin>Admins { get; set; }

    }
}

WebApplication1/Models/ErrorViewModel.cs
using System;

namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Personel
    {
        [Key]
        public int PersonelID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Sehir { get; set; }
        public int BirimID { get; set; }
        public Birim Birim { get; set; }
    }
}

WebApplication1/Models/keyAttribute.cs
using System;

namespace WebApplication1.Models
{
    internal class keyAttribute : Attribute
    {
    }
}

WebApplication1/Controllers/BirimController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class BirimController : Controller
    {
        Context c = new Context();
        public IActionResult Index()
        {
            var degerler = c.Birims.ToList();
            return View(degerler);
        }
        [HttpGet]
        public IActionResult YeniBirim()
        {
            return View();
        }
        [HttpPost]
        public IActionResult YeniBirim(Models.Birim a)
        {
            c.Birims.Add(a);
            c.SaveChanges();
            return RedirectToAction("Index");

        }
        public IActionResult BirimSil(int id)
        {
            var dep = c.Birims.Find(id);
            c.Birims.Remove(dep);
            c.SaveChanges();
            return RedirectToAction("Index");

        }
        public IActionResult BirimGetir(int id)
        {
            var depart = c.Birims.Find(id);
            return View("BirimGetir", depart);
        }
        public IActionResult BirimGuncelle(Birim d)
        {
            var dep = c.Birims.Find(d.BirimID);
            dep.BirimAd = d.BirimAd;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult BirimDetay(int id)
        {
            var degerler = c.Personels.Where(x => x.BirimID == id).ToList();
            var brmad = c.Birims.Where(x => x.BirimID == id).Select(y => y.BirimAd).FirstOrDefault();
            ViewBag.brm = brmad;
            return View(degerler);
        }
    }
}

WebApplication1/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace WebApplication1.Controllers
{
    public class LoginController : Controller
    {
        Context c = new Context();
        [HttpGet]
        public IActionResult GirisYap()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> GirisYap(Admin p)
        {
            var bilgiler = c.Admins.FirstOrDefault(x => x.Kullanici == p.Kullanici &&
              x.Sifre == p.Sifre);
            if(bilgiler!= null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name,p.Kullanici)
                };
                var useridentity = new ClaimsIdentity(claims, "Login");
                ClaimsPrincipal principal = new ClaimsPrincipal(useridentity);
                await HttpContext.SignInAsync(principal);
                return RedirectToAction("Index","Personel");
            }
            return View();

        }
        [HttpGet]
        public async Task<IActionResult> CikisYap()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("GirisYap", "Login");
        }
    }
}

WebApplication1/Controllers/PersonelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class PersonelController : Controller
    {
        Context c = new Context();
        [Authorize]
        public IActionResult Index()
        {
            var degerler = c.Personels.Include(x => x.Birim).ToList();
            return View(degerler);
        }
        [HttpGet]
        public IActionResult YeniPersonel()
        {
            List<SelectListItem> degerler = (from x in c.Birims.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = x.BirimAd,
                                                 Value = x.BirimID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            return View();
        }
        [HttpPost]
        public IActionResult YeniPersonel(Models.Personel p)
        {
            var per = c.Birims.Where(x => x.BirimID == p.Birim.BirimID).FirstOrDefault();
            p.Birim = per;
            c.Personels.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

WebApplication1/Views/Birim/BirimDetay.cshtml
@using WebApplication1.Models
@model List<Personel>

<br />
<h2>@ViewBag.brm</h2>
<br/>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>

    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.PersonelID</td>
            <td>@x.Ad</td>
            <td>@x.Soyad</td>
            <td>@x.Sehir</td>
        </tr>
    }
</table>

WebApplication1/Views/Birim/BirimGetir.cshtml
@model WebApplication1.Models.Birim
@using (Html.BeginForm("BirimGuncelle", "Birim", FormMethod.Post))
{
    <br />
    <b>Birim ID</b>
    @Html.TextBoxFor(x => x.BirimID, new { @class = "form-control" })
    <br />
    <b>Departman Adı</b>
    @Html.TextBoxFor(x => x.BirimAd, new { @class = "form-control" })
    <br />

    <button class="btn btn-success">Güncelle</button>
}

WebApplication1/Views/Birim/BirimGuncelle.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

WebApplication1/Views/Birim/Index.cshtml
@using WebApplication1.Models
@model List<Birim>

<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>birim</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.BirimID</td>
            <td>@x.BirimAd</td>
            <td><a href="/Birim/BirimSil/@x.BirimID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Birim/BirimGetir/@x.BirimID" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Birim/BirimDetay/@x.BirimID" class="btn btn-info">Detaylar</a></td>
        </tr>
    }
</table>
<a href="/Birim/YeniBirim" , class="btn btn-primary">Yeni Birim</a>

WebApplication1/Views/Birim/YeniBirim.cshtml
@model WebApplication1.Models.Birim
<br/>
<form class="form-group" method="post">
    <b>Birim Adı</b>
    @Html.TextBoxFor(x=>x.BirimAd, new { @class = "form-control"})
<br/>
    <button class="btn btn-info">Birim Ekle </button>
</form>

WebApplication1/Views/Login/CikisYap.cshtml
@{
    ViewData["Title"] = "CikisYap";
}

<h1>CikisYap</h1>

WebApplication1/Views/Login/GirisYap.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="tr">
<head>
    <title>Giriş</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/Login_v2/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v2/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v2/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v2/fonts/iconic/css/material-design-iconic-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v2/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v2/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v2/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v2/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v2/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v2/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Login_v2/css/main.css">
    <!--===============================================================================================-->
</head>
<body>

    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form class="login100-form validate-form" method="post" > 
                    <span class="login100-form-title p-b-26">
                        <h2>Hoşgeldiniz</h2>
                    </span>

                    <div class="wrap-input100 validate-input" data-validate="Kullanıcı adınızı giriniz">
                        <input class="input100" type="text" name="Kullanici">
                        <span class="focus-input100" data-placeholder="Kullanıcı Adı"></span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate="Şifrenizi giriniz">
                        <span class="btn-show-pass">
                            <i class="zmdi zmdi-eye"></i>
                        </span>
                        <input class="input100" type="password" name="Sifre">
                        <span class="focus-input100" data-placeholder="Şifre"></span>
                    </div>

                    <div class="container-login100-form-btn">
                        <div class="wrap-login100-form-btn">
                            <div class="login100-form-bgbtn"></div>
                            <button class="login100-form-btn">
                                Giriş
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div id="dropDownSelect1"></div>

    <!--===============================================================================================-->
    <script src="~/Login_v2/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v2/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v2/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Login_v2/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v2/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v2/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/Login_v2/vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v2/vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v2/js/main.js"></script>
</body>
</html>

WebApplication1/Views/Personel/Index.cshtml
@using WebApplication1.Models
@model List<Personel>

<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
        <th>Departman</th>
        <th>Sil</th>
        <th>Güncelle</th>

    </tr>
    @foreach (var x in Model)
    {
<tr>
    <td>@x.PersonelID</td>
    <td>@x.Ad</td>
    <td>@x.Soyad</td>
    <td>@x.Sehir</td>
    <td>@x.Birim.BirimAd</td>
    <td><a href="/Personel/PersonelSil/@x.PersonelID" class="btn btn-danger">Sil</a></td>
    <td><a href="/Personel/PersonelGuncelle/@x.PersonelID" class="btn btn-success">Güncelle</a></td>
</tr>
    }
</table>
<a href="/Personel/YeniPersonel" , class="btn btn-primary">Yeni Birim</a>

WebApplication1/Views/Personel/YeniPersonel.cshtml
@model WebApplication1.Models.Personel
<br />
<form class="form-group" method="post">
    <b>Personel Adı</b>
    @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    <br />
    <b>Personel Soyaddı</b>
    @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
    <br />
    <b>Personel Şehri</b>
    @Html.TextBoxFor(x => x.Sehir, new { @class = "form-control" })
    <br />
    <b>BİRİM </b>
    @Html.DropDownListFor(x => x.Birim.BirimID, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Personel Ekle </button>


</form>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Sıla Öztürk</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
        <h3 class="w3-bar-item">Menü</h3>
        <a href="/Birim/Index" class="w3-bar-item w3-button">BİRİMLER</a>
        <a href="/Personel/Index" class="w3-bar-item w3-button">PERSONELLER</a>
        <a href="#" class="w3-bar-item w3-button">HAKKIMIZDA</a>
        <a href="/Login/CikisYap" class="w3-bar-item w3-button">ÇIKIŞ</a>
    </div>
    <!-- Page Content -->
    <div style="margin-left:15%">

        <div class="w3-container w3-teal">
            <h1>ASP.NET CORE MVC  DENEMELERİ</h1>
        </div>

        <div class="w3-container">
            @RenderBody()
        </div>

    </div>

</body>
</html>